FROM registry.cn-shanghai.aliyuncs.com/c7n/javabase:0.9.0
COPY app.jar /manager-service.jar
COPY dist /dist
RUN chmod +x /dist/env.sh \
    && chown -R www-data:www-data /manager-service.jar /dist
USER www-data
CMD /dist/env.sh java $JAVA_OPTS $SKYWALKING_OPTS -jar /manager-service.jar